[package]
name = "oscillation"
version = "0.1.0"
edition = "2024"

[dependencies]
moddef = "0.2.6"
rand = "0.9.1"
num-traits = "0.2.19"
num-complex = "0.4.6"
serde = {version = "1.0.219", features = ["derive"]}
GSL = "7.0.0"

[dev-dependencies]
plotters = "0.3.7"
linspace = "0.1.1"